spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/agency_esther
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
